### ISSUE TITLE
the slider right button not working?  

### ISSUE THREAD

**Issue by Dave00** [gibbok/jquery-slidertv#1]
The right slider button not working for the mouse?  Left slider button works.

**Comment by gibbok** [comment]
Hi,
I have tested included example (horizontal.html) using mouse click on left/right arrow icons and using the keypad arrow left/right but I cannot reproduce your error.

Test executed for release 1.0.9 on:
Opera   36.0.2130.32
Chrome  49.0.2623.87 m
Firefox 45.0

If you have an issue on a specific implementation, please provide me an example. I'll try to help.

Thanks for reporting.

**Comment by Dave00** [comment]
Thanks - downloaded from jqueryscripts.net under latest plugins.   The demo working so I must have something wrong on my side.   Thanks, Dave.

Great slider.  Thanks again.

Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------
