### ISSUE TITLE
Activate href with Enter key?

### ISSUE THREAD

**Issue by Green-1** [gibbok/jquery-slidertv#2]
Dear gibbok,
Congrats to this awesome plugin. I am a total newbie in the jquery-world. Is there a way to activate the href content of the active slider element with the enter key? I would like to use your slider as a local "application launcher" on a PC. 
Thanks!
Regards, Alex

**Comment by gibbok** [comment]
Hi Alex,
you could consider adding in your markup an `<a>` tag with `href` to your movie and you can detect when User click on it using jquery [.click() ](https://api.jquery.com/click/)

You can see an actual implementation here: http://atonvision.github.io/mediadata/
I am glad you enjoy jquery-slidertv :).
Thanks.
