### ISSUE TITLE
疑问，学习

### ISSUE THREAD

**Issue by margin-0** [gibbok/jquery-slidertv#5]
你好，最近由于项目需求接触到了你写的插件，但是最初版式网上的一个有现成效果的DEMO，我是小白类型的，不能完全看懂这个插件，在用的时候，我需要的是动态加载数据即图片等，我遇到了问题就是如果页面已经渲染了，再次加载的时候就没有执行init方法像是原本的这个方法被覆盖掉了的感觉，所以后来加载的数据没有被position定位，希望您能对我指点一二，或者讲解一下关于插件动态加载需要注意的问题，非常感谢

**Comment by gibbok** [comment]
Question answered here:
https://github.com/gibbok/jquery-slidertv/issues/6
