### ISSUE TITLE
question

### ISSUE THREAD

**Issue by margin-0** [gibbok/jquery-slidertv#6]
Hello, I’m writing to ask your kindly help. The thing is that : I handle a project which need your plug-in and I find a using demo in the web . But for lack of experience I’m still a green hand. When using it to dynamically load data like picture and others, I find if the wed page has been rent, it can’t be “in it” when I loading next time . It seems like the progress “in it ” has been covered , thus the following loading data haven’t been positioned. 
   Hope you could give me some suggestion or some special point that need to be careful treated when loading data. Thanks very much.

**Comment by gibbok** [comment]
Hi, I hope I understood your question properly. A solution could be:

- Load your data using AJAX.
- After the data is loaded successfully render your HTML markup.
- Initiate the plugin calling`.sliderTV();` after you DOM has been rendered.

Example:
```javascript
// load your data
$.ajax({url: "api.json", success: function(result){
    // render you html
   // ...
   // initiate sliderTV
    $('#sliderTV').sliderTV();
}});
```
If you need more assistance, please post on jsfiddle a minimal working example of your code and I will have a look at it.

**Comment by margin-0** [comment]
你好，谢谢你给我的回复，我想再详细描述一下我的问题，恩，我之前按找过你给我说的方法进行加载，这个也没有问题，但是当加载了一次数据后，例如：$('#sliderTV').sliderTV();这样之后，我再次请求数据加载像分页请求这样的，同样的方法加入我的DOM，然后在调用$('#sliderTV').sliderTV();但是我发现之后加载的数据DOM并没有按照定位那样排列，还有一个问题就是，我每一次使用$('#sliderTV').sliderTV()这个方法，DOM加载进去都会以position重新定位，所以他的left值都是从0开始的，我想过几个方法试图去改变这个left值，已达到每次分页请求之后它加载了数据，展示的都是接下来的数据，而不是从头开始，但是都失败了，我想我可能还是不能理解您插件的精髓，所以想通过这向您询问关于left初始值的改变是否有好的方法呢？再次感谢您

**Comment by gibbok** [comment]
Hi, you could find reference to the API here:
https://github.com/gibbok/jquery-slidertv/blob/master/docs/sliderTV.md

At the following link also a working example:
https://github.com/gibbok/jquery-slidertv/blob/master/examples/js/horizontal.js

Thanks

**Comment by guyuleo** [comment]
Dobrý den, děkuji za to, že moji odpověď, bych chtěl rozvést mou otázku, uh, mluvil jsem stisknout předtím, než mi dát metodu k načtení, to není problém, ale když načteného údaje, například, : $ ('# sliderTV ") sliderTV (), takže jsem znovu požádat o načtení dat jako žádost stránkovacího tuto stejnou metodu k mému DOM, pak volání $ (' # sliderTV") sliderTV (); .. ale našel jsem po naložení DOM dat a nejsou uspořádány v souladu s umístěním, protože to je problém je, že jsem každé použití $ ('# sliderTV "). sliderTV () tato metoda, DOM bude načten do polohy re-lokalizovat, takže se levá hodnoty jsou od 0 počátku, myslel jsem si z několika způsobů, jak se snaží změnit hodnotu vlevo, jsme dosáhli ji po každém požadavku na stránku data jsou vložena, jsou zobrazeny následující údaje, spíše než začínat od nuly, ale selhaly, myslím, že bych mohl ještě nechápou podstatu svého plug-in, tak jsem chtěl, aby ti to zeptat změnou počáteční hodnoty na levé straně je tam dobrý způsob, jak to udělat? Ještě jednou děkuji

**Comment by margin-0** [comment]
Thanks very much.
