### ISSUE TITLE
more than one horizontal slider

### ISSUE THREAD

**Issue by jamesAnderson99** [gibbok/jquery-slidertv#7]
Hello,

The slider looks very cool thanks for providing. What I want to know is if it possible to use two horizontal sliders one below another and navigation would be possible between each of them.

For example if any poster is focused on first horizontal slider when down button clicked on the keyboard it should focus on the second horizontal slider. I would be glad if you can provide an example or any idea.

Thanks again!

**Comment by gibbok** [comment]
Hi, yes it is possible, you can have a look at this [documentation](https://github.com/gibbok/jquery-slidertv/blob/master/docs/sliderTV.md).

**Comment by jjfster** [comment]
I am also interested in doing this, but it is not clear just from the documentation how to switch between different sliderTV instances when the down or up arrows are pressed.  I can sniff for the up and down arrow, but do I just switch focus from one sliderTV.id to the other?  That doesn't seem to work for me.  Any sample code available for this?  Thanks for the slider!
