### ISSUE TITLE
Uncaught TypeError: Cannot read property 'css' of null

### ISSUE THREAD

**Issue by parisaabasian** [gibbok/jquery-slidertv#8]
I am rendering multiple sliders with AJAX with different ids ,but I am getting this error
I`ve used $.when( ).done(function() { ...
so that I make sure the sliders have been rendered,
I don`t know what am I doing wrong 
can you help me please

**Comment by gibbok** [comment]
Please create a minimal reproducible example where the issue shows up, so I can try to help you out. Thanks!

**Comment by parisaabasian** [comment]
@gibbok Ok I`ll do that,but for nw just tell me is that possible to render the slider with ajax call?because the slider works only after page is loaded
thank you

**Comment by gibbok** [comment]
Yes it is possible.

**Comment by parisaabasian** [comment]
@gibbok 
take a look at this : https://codepen.io/pariabasi/pen/YOMzww
that`s how I rendered my sliders
if anything else is required just let me know

**Comment by gibbok** [comment]
Hi, first make sure you load the slider in you code, link to js file should be added in the header before your custom code.
Second make sure to wrap your code inside `$( document ).ready()`.
